name: Install Python dev requirements on Python 3.11

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11-dev"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --upgrade pip
    - run: sudo apt-get install gdal-bin
    - run: pip install -r requirements-dev.txt

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11-dev"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --upgrade pip
    - run: brew install gdal
    - run: pip install -r requirements-dev.txt

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11-dev"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --upgrade pip pipwin
    - run: pipwin install gdal
    - run: pipwin install fiona
    - run: pip install -r requirements-dev.txt
